# -*- coding: utf-8 -*-
"""Untitled33.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18LpVoUDso-_zfaiZgT_wEjGSp4XNiyCq
"""

# ============================================
# DIGITAL WEDDING INVITE APP - STREAMLIT
# ============================================
# FEATURES:
# ✔ Mobile Responsive
# ✔ Flipbook / Page Turning Effect
# ✔ 2 Background Music Options
# ✔ Animated Entry Screen
# ✔ PDF Invite Embedded
# ✔ Floating Floral Theme
# ✔ Countdown Timer
# ✔ Wedding Schedule Timeline
# ✔ Download Invite Option
# ✔ Fully Deployable on Streamlit Cloud
# ✔ GitHub Ready Structure
# ============================================


# =========================
# FILE STRUCTURE
# =========================
#
# wedding_invite_app/
#
# ├── app.py
# ├── requirements.txt
# ├── assets/
# │   ├── wedding_invite.pdf
# │   ├── jashne_bahara.mp3
# │   ├── mangalyam_sathiya.mp3
# │   ├── cover.jpg
# │   ├── page2.jpg
# │   ├── page3.jpg
# │
# ├── .streamlit/
# │   └── config.toml
# │
# └── README.md
#
# =========================


# ============================================
# app.py
# ============================================

import streamlit as st
from streamlit.components.v1 import html
import base64
from datetime import datetime

st.set_page_config(
    page_title="Manish ❤️ Manasi Wedding",
    page_icon="💍",
    layout="centered",
    initial_sidebar_state="collapsed"
)

# ============================================
# CUSTOM CSS
# ============================================

st.markdown("""
<style>

html, body, [class*="css"] {
    font-family: 'Georgia', serif;
    background: linear-gradient(to bottom, #fff8f0, #ffe6ea);
    overflow-x: hidden;
}

/* Hide Streamlit Branding */
#MainMenu {visibility: hidden;}
footer {visibility: hidden;}
header {visibility: hidden;}

.main-title{
    text-align:center;
    font-size:42px;
    color:#8B0000;
    font-weight:bold;
    margin-top:20px;
}

.sub-title{
    text-align:center;
    font-size:22px;
    color:#5c4033;
}

.gold-line{
    height:2px;
    background:gold;
    margin:15px 0;
}

.countdown{
    text-align:center;
    font-size:24px;
    color:#b22222;
    padding:10px;
    border-radius:15px;
    background:white;
    box-shadow:0 4px 10px rgba(0,0,0,0.15);
}

.card{
    background:white;
    border-radius:25px;
    padding:20px;
    margin-top:20px;
    box-shadow:0 8px 20px rgba(0,0,0,0.15);
}

.flipbook{
    border-radius:20px;
    overflow:hidden;
    margin-top:20px;
}

.music-box{
    background:#fff;
    padding:10px;
    border-radius:20px;
    box-shadow:0 4px 15px rgba(0,0,0,0.15);
}

.schedule-box{
    background:#fffaf0;
    padding:15px;
    border-left:5px solid maroon;
    margin-top:10px;
    border-radius:15px;
}

.invite-btn{
    background:#8B0000;
    color:white;
    padding:10px 25px;
    border-radius:50px;
    text-align:center;
}

.mobile-note{
    text-align:center;
    color:gray;
    font-size:13px;
}

</style>
""", unsafe_allow_html=True)


# ============================================
# HERO SECTION
# ============================================

st.markdown("""
<div class='main-title'>
💖 शुभ विवाह 💖
</div>

<div class='sub-title'>
Manish ❤️ Manasi
</div>

<div class='sub-title'>
19 June 2026
</div>
""", unsafe_allow_html=True)


# ============================================
# COUNTDOWN TIMER
# ============================================

wedding_date = datetime(2026, 6, 19)
today = datetime.now()

remaining = wedding_date - today

days = remaining.days
hours = remaining.seconds // 3600

st.markdown(f"""
<div class='countdown'>
⏳ Wedding Countdown <br><br>
<b>{days} Days {hours} Hours Left</b>
</div>
""", unsafe_allow_html=True)


# ============================================
# MUSIC PLAYER
# ============================================

st.markdown("<br>", unsafe_allow_html=True)

st.markdown("""
<div class='music-box'>
<h3 style='text-align:center;color:maroon;'>🎵 Wedding Music</h3>
</div>
""", unsafe_allow_html=True)

music = st.selectbox(
    "Choose Background Music",
    ["Jashn-E-Bahara", "Mangalyam"]
)

if music == "Jashn-E-Bahara":
    audio_file = open("assets/jashne_bahara.mp3", "rb")
else:
    audio_file = open("assets/mangalyam_sathiya.mp3", "rb")

audio_bytes = audio_file.read()

st.audio(audio_bytes, format="audio/mp3")


# ============================================
# FLIPBOOK PDF VIEWER
# ============================================

st.markdown("""
<div class='card'>
<h2 style='text-align:center;color:#8B0000;'>
📖 Wedding Invitation
</h2>
</div>
""", unsafe_allow_html=True)

with open("assets/wedding_invite.pdf", "rb") as pdf_file:
    base64_pdf = base64.b64encode(pdf_file.read()).decode('utf-8')

pdf_display = f'''
<iframe
src="data:application/pdf;base64,{base64_pdf}"
width="100%"
height="700"
type="application/pdf">
</iframe>
'''

st.markdown(pdf_display, unsafe_allow_html=True)


# ============================================
# FLIP ANIMATION SECTION
# ============================================

st.markdown("""
<div class='card'>
<h2 style='text-align:center;color:#8B0000;'>
✨ Digital Flipbook Invite ✨
</h2>
</div>
""", unsafe_allow_html=True)

flip_html = """
<!DOCTYPE html>
<html>
<head>
<style>

body{
background:#fffaf0;
}

.flipbook{
width:100%;
height:500px;
position:relative;
perspective:1500px;
margin:auto;
}

.page{
width:100%;
height:100%;
position:absolute;
transform-origin:left;
transition:transform 1s;
cursor:pointer;
}

.page img{
width:100%;
height:100%;
object-fit:cover;
border-radius:15px;
box-shadow:0px 10px 25px rgba(0,0,0,0.3);
}

.page.flipped{
transform:rotateY(-180deg);
}

</style>
</head>

<body>

<div class="flipbook">

<div class="page" id="page1" style="z-index:3">
<img src="https://i.imgur.com/8Km9tLL.jpg">
</div>

<div class="page" id="page2" style="z-index:2">
<img src="https://i.imgur.com/z7mG3L8.jpg">
</div>

<div class="page" id="page3" style="z-index:1">
<img src="https://i.imgur.com/VxKRa7B.jpg">
</div>

</div>

<script>

const pages = document.querySelectorAll('.page');

pages.forEach((page, index)=>{
    page.addEventListener('click', ()=>{
        page.classList.toggle('flipped');
    });
});

</script>

</body>
</html>
"""

html(flip_html, height=550)


# ============================================
# WEDDING EVENTS
# ============================================

st.markdown("""
<div class='card'>
<h2 style='text-align:center;color:#8B0000;'>
📅 Wedding Schedule
</h2>
</div>
""", unsafe_allow_html=True)

st.markdown("""
<div class='schedule-box'>
<h4>18 June 2026</h4>
Ganesh Pujan – 8:00 AM<br>
Mandap Pratishtha – 11:00 AM<br>
Haldi Ceremony – 4:00 PM<br>
Sangeet Sandhya – 8:00 PM
</div>
""", unsafe_allow_html=True)

st.markdown("""
<div class='schedule-box'>
<h4>19 June 2026</h4>
Baraat Prasthan – 10:00 AM<br>
Shubh Lagna – 12:00 PM<br>
Lunch & Blessings – 1:00 PM
</div>
""", unsafe_allow_html=True)


# ============================================
# GOOGLE MAP
# ============================================

st.markdown("""
<div class='card'>
<h2 style='text-align:center;color:#8B0000;'>
📍 Venue
</h2>

<p style='text-align:center;font-size:20px;'>
Dream World Resort<br>
Indore
</p>

</div>
""", unsafe_allow_html=True)

st.link_button(
    "Open Google Maps",
    "https://maps.google.com"
)


# ============================================
# DOWNLOAD BUTTON
# ============================================

with open("assets/wedding_invite.pdf", "rb") as file:
    st.download_button(
        label="📥 Download Wedding Invite",
        data=file,
        file_name="Wedding_Invite.pdf",
        mime="application/pdf"
    )


# ============================================
# FOOTER
# ============================================

st.markdown("""
<br><br>

<div style='text-align:center;color:gray;'>
Made with ❤️ for Manish & Manasi
</div>

<div class='mobile-note'>
Optimized for Mobile Viewing 📱
</div>
""", unsafe_allow_html=True)

